### ISSUE TITLE
limit 過ぎたやつの取り扱いについて

### ISSUE THREAD

**Issue by oshamashama** [oshamashama/owarukana#1]
起票時点では大丈夫だけど，期限を過ぎたやつは表示が恐らく負になってかわいくない

過ぎて1日は終わったメッセージに
それ以降は表示しない，とかで良いかな？

**Comment by Okabe-Junya** [comment]
良いですね。

履歴を残さなくて良い && うまぶりをやりたかったら、`deadline.json` から消すcronがあっても良いですね

**Comment by Okabe-Junya** [comment]
yosasou
