### ISSUE TITLE
卒業

### ISSUE THREAD

**Issue by Okabe-Junya** [oshamashama/owarukana#2]
卒業までのカウントダウンをやりたくないですか？

**Comment by Okabe-Junya** [comment]
@oshamashama friendly ping

**Comment by Okabe-Junya** [comment]
deadlineかと言われると怪しい気もしますが

**Comment by oshamashama** [comment]
いいね、PRもらえればマージします
https://github.com/oshamashama/owarukana/blob/main/src/deadline.json

**Comment by Okabe-Junya** [comment]
クイックレスポンスで嬉しい。やります
